services:
  - type: web
    name: search-engine-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: USE_MONGODB
        value: true
      - key: PORT
        value: 5001
